package com.networktoolbox.core.common.diagnostic

enum class DiagnosticObservationCode {
    ACTIVE_NETWORK_AVAILABLE,
    CONNECTION_TYPE,
    LOCAL_ADDRESS,
    GATEWAY_ADDRESS,
    DNS_CONFIGURATION,
    VALIDATED_NETWORK,
    VPN_ACTIVE,
    CAPTIVE_PORTAL,
    GATEWAY_PROBE_OUTCOME,
    PUBLIC_TCP_OUTCOME,
    DNS_OUTCOME,
    TARGET_TCP_OUTCOME,
    NETWORK_CHANGED,
}
enum class DiagnosticCheckCode {
    NETWORK_STATE,
    IP_CONFIGURATION,
    GATEWAY,
    PUBLIC_CONNECTIVITY,
    DNS_RESOLUTION,
    TARGET_CONNECTIVITY,
    ADVANCED_PATH,
    NETWORK_STABILITY,
}

enum class DiagnosticFindingCode {
    NO_ACTIVE_NETWORK,
    NETWORK_STATE_UNCONFIRMED,
    IP_CONFIGURATION_UNCONFIRMED,
    GATEWAY_PROBE_NO_RESPONSE,
    LOCAL_OR_UPSTREAM_PATH_UNCONFIRMED,
    PUBLIC_CONNECTIVITY_UNCONFIRMED,
    DNS_RESOLUTION_FAILURE,
    DNS_NXDOMAIN,
    FAKE_IP_CONTEXT,
    VPN_ACTIVE,
    CAPTIVE_PORTAL_CONTEXT,
    TARGET_TCP_REFUSED,
    TARGET_TCP_TIMEOUT,
    NETWORK_APPEARS_NORMAL,
}

enum class DiagnosticRecommendationCode {
    RETRY_DIAGNOSTIC,
    CHECK_WIFI_OR_MOBILE_NETWORK,
    CHECK_ROUTER_WAN,
    CHECK_PRIVATE_DNS_VPN_PROXY,
    CHECK_CAPTIVE_PORTAL,
    COMPARE_ANOTHER_NETWORK,
    RUN_TARGET_CHECK,
    VIEW_TRACEROUTE,
}
